# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'AV Linux Pool'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo What files are in this folder?
    ls
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: 'pip3 install checkov'
  displayName: Install checkov

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: 'checkov -f av-aws-resources.tf --skip-check CKV_DOCKER_*'
  displayName: Checkov source code scan
  continueOnError: true

